"""initial schema (04-db.md)

Revision ID: 7cbecbc6d800
Revises: 
Create Date: 2026-09-16 00:22:30.284977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbecbc6d800'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_id', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.CheckConstraint("category IN ('bootcamp_required','auxiliary')", name='ck_field_definitions_category'),
    sa.CheckConstraint("scope IN ('case','item')", name='ck_field_definitions_scope'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inquiry_code', sa.String(length=30), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('requester', sa.String(length=255), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','final')", name='ck_inquiries_status'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inquiry_code')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=30), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('tool_call_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("agent_name IN ('agent01_extraction','agent02_verification')", name='ck_agent_runs_agent_name'),
    sa.CheckConstraint("stage IN ('uploading','extracting','structuring','reviewing','completed','failed','stopped')", name='ck_agent_runs_stage'),
    sa.CheckConstraint("status IN ('running','succeeded','failed','stopped')", name='ck_agent_runs_status'),
    sa.CheckConstraint("trigger IN ('new_upload','additional_upload')", name='ck_agent_runs_trigger'),
    sa.CheckConstraint('progress_percent >= 0 AND progress_percent <= 100', name='ck_agent_runs_progress_percent'),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("format IN ('excel','word','pdf')", name='ck_exports_format'),
    sa.CheckConstraint("state IN ('draft','final')", name='ck_exports_state'),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inquiry_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('reason_type', sa.String(length=20), nullable=True),
    sa.Column('is_web_supplemented', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.String(length=10), nullable=True),
    sa.Column('confirmed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confirmed_by IS NULL OR confirmed_by IN ('ai','web','user')", name='ck_inquiry_fields_confirmed_by'),
    sa.CheckConstraint("reason_type IS NULL OR reason_type IN ('missing','conflict','ambiguous','multiple_candidates','parse_error')", name='ck_inquiry_fields_reason_type'),
    sa.CheckConstraint("status IN ('ok','review')", name='ck_inquiry_fields_status'),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['field_definition_id'], ['field_definitions.id'], ),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inquiry_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("file_type IN ('xlsx','pdf','eml')", name='ck_inquiry_files_type'),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inquiry_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('item_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inquiry_item_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inquiry_item_id', sa.Integer(), nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('reason_type', sa.String(length=20), nullable=True),
    sa.Column('is_web_supplemented', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.String(length=10), nullable=True),
    sa.Column('confirmed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confirmed_by IS NULL OR confirmed_by IN ('ai','web','user')", name='ck_inquiry_item_fields_confirmed_by'),
    sa.CheckConstraint("reason_type IS NULL OR reason_type IN ('missing','conflict','ambiguous','multiple_candidates','parse_error')", name='ck_inquiry_item_fields_reason_type'),
    sa.CheckConstraint("status IN ('ok','review')", name='ck_inquiry_item_fields_status'),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['field_definition_id'], ['field_definitions.id'], ),
    sa.ForeignKeyConstraint(['inquiry_item_id'], ['inquiry_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inquiry_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('inquiry_item_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=10), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope IN ('case','item')", name='ck_inquiry_notes_scope'),
    sa.CheckConstraint("source_type IS NULL OR source_type IN ('pdf','excel','eml','web')", name='ck_inquiry_notes_source_type'),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.ForeignKeyConstraint(['inquiry_item_id'], ['inquiry_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parsed_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['inquiry_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inquiry_field_id', sa.Integer(), nullable=True),
    sa.Column('inquiry_item_field_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=10), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_location', sa.String(length=255), nullable=True),
    sa.Column('quoted_text', sa.Text(), nullable=True),
    sa.Column('web_url', sa.String(length=500), nullable=True),
    sa.Column('web_source_name', sa.String(length=255), nullable=True),
    sa.Column('web_referenced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_explicit_correction', sa.Boolean(), nullable=False),
    sa.Column('superseded_value', sa.Text(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('pdf','excel','eml','web')", name='ck_field_candidates_source_type'),
    sa.CheckConstraint('(inquiry_field_id IS NOT NULL AND inquiry_item_field_id IS NULL) OR (inquiry_field_id IS NULL AND inquiry_item_field_id IS NOT NULL)', name='ck_field_candidates_exactly_one_parent'),
    sa.ForeignKeyConstraint(['inquiry_field_id'], ['inquiry_fields.id'], ),
    sa.ForeignKeyConstraint(['inquiry_item_field_id'], ['inquiry_item_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_candidates')
    op.drop_table('parsed_documents')
    op.drop_table('inquiry_notes')
    op.drop_table('inquiry_item_fields')
    op.drop_table('extraction_results')
    op.drop_table('inquiry_items')
    op.drop_table('inquiry_files')
    op.drop_table('inquiry_fields')
    op.drop_table('exports')
    op.drop_table('agent_runs')
    op.drop_table('inquiries')
    op.drop_table('users')
    op.drop_table('field_definitions')
    # ### end Alembic commands ###
